### PR TITLE
Unstaged changes

### PR DESCRIPTION
**Pull request by anishaas**

### CODE REVIEW

**Comment by jah2488** [comment]
Why is this PR Called unstaged changes.

**Comment by anishaas** [comment]
Mmm that wasn't intentional -- I hit the button before changing it. I tried a pull request before and the changesI made on my branch weren't showing up on here.

**Comment by anishaas** [comment]
I had way more commits than one

**Comment by anishaas** [comment]
This is from my command line before I made this pull request. The changes after the dashed line weren't showing up when I tried the pull request earlier: 

git fetch upstream && git rebase upstream/master
First, rewinding head to replay your work on top of it...
Applying: Unstaged changes
Using index info to reconstruct a base tree...
M   db/schema.rb
Falling back to patching base and 3-way merge...
Applying: Unstaged changes
Using index info to reconstruct a base tree...
M   Gemfile
M   app/assets/javascripts/components/accept.js.jsx
M   db/seeds.rb
Falling back to patching base and 3-way merge...

## No changes -- Patch already applied.

Applying: styling on events page fixed
Applying: Attending button disappears upon clicking
Applying: Changed the Gemfile back to correct version
Applying: Fixed accepting event button

**Pull request closed without merging**
